Add a step to check the format of the tag input

diff --git a/.github/actions/create-branch-tag/action.yml b/.github/actions/create-branch-tag/action.yml
--- a/.github/actions/create-branch-tag/action.yml
+++ b/.github/actions/create-branch-tag/action.yml
@@ -24,8 +24,8 @@ runs:
       run: |
         TAG_FORMAT="^[0-9]\.[0-9]\.[0-9](-test-[1-3])*$"
         TRIMMED_TAG_NAME=$(echo "$TAG_NAME" | xargs)
-        if ! [[ $TRIMMED_TAG_NAME =~ TAG_FORMAT ]]; then
-          echo "::error::The tag name provided doesn't respect the format (tag name: $TRIMMED_TAG_NAME)."
+        if ! [[ $TRIMMED_TAG_NAME =~ $TAG_FORMAT ]]; then
+          echo "::error::The tag name provided doesn't respect the format expected (tag: $TRIMMED_TAG_NAME)."
           exit 1
         fi
     - name: "Create a branch and tag"
