Undo retries refactor

diff --git a/.github/actions/e2e/run-log-tests/action.yml b/.github/actions/e2e/run-log-tests/action.yml
--- a/.github/actions/e2e/run-log-tests/action.yml
+++ b/.github/actions/e2e/run-log-tests/action.yml
@@ -1,17 +1,35 @@
-name: 'Run Tests'
+name: 'Run E2E Tests with Retry & Upload Logs'
 description: 'Runs E2E tests with retry & upload logs and screenshots'
 
 runs:
   using: "composite"
   steps:
-    - name: Run E2E Tests
-      shell: bash
+    - name: First Run E2E Tests
+      id: first_run_e2e_tests
+      # Use +e to trap errors when running E2E tests.
+      shell: /bin/bash +e {0}
       run: |
-        set -e
-        npm run test:e2e-ci || {
-          echo "::notice::Some tests failed, retrying only failed tests with --last-failed flag"
-          npx playwright test --config=tests/e2e/playwright.config.ts --grep-invert @todo --last-failed
-        }
+        npm run test:e2e-ci
+
+        if [[ -f "$E2E_RESULT_FILEPATH" ]]; then
+          E2E_NUM_FAILED_TEST_SUITES=$(cat "$E2E_RESULT_FILEPATH" | jq '.stats["unexpected"]')
+          echo "FIRST_RUN_FAILED_TEST_SUITES=$(echo $E2E_NUM_FAILED_TEST_SUITES)" >> $GITHUB_OUTPUT
+          if [[ ${E2E_NUM_FAILED_TEST_SUITES} -gt 0 ]]; then
+            echo "::notice::${E2E_NUM_FAILED_TEST_SUITES} test suite(s) failed in the first run but we will try (it) them again in the second run."
+            exit 0
+          fi
+        else
+          echo "FIRST_RUN_FAILED_TEST_SUITES=0" >> $GITHUB_OUTPUT
+          exit 0
+        fi
+
+    # Retry failed E2E tests
+    - name: Re-try Failed E2E Files
+      if: ${{ steps.first_run_e2e_tests.outputs.FIRST_RUN_FAILED_TEST_SUITES > 0  }}
+      shell: bash
+      # Filter failed E2E files from the result JSON file, and re-run them.
+      run: |
+        npm run test:e2e-ci $(cat $E2E_RESULT_FILEPATH | jq -r '[.suites[] | (if has("suites") then .suites[] | .specs[] else .specs[] end) | select(.tests[].status == "unexpected") | .file] | unique | .[]')
 
     # Archive screenshots if any
     - name: Archive e2e test screenshots & logs
