check fo branch

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,15 @@
 #!/bin/bash
 . "$(dirname "$0")/_/husky.sh"
 
-# Warn about the push and ask for confirmation
-read -p "Are you sure you want to push.? (y/n): " confirm
-if [ "$confirm" != "y" ]; then
-  echo "Push aborted"
-  exit 1
+# Allows us to read user input below, redirects script's input to the terminal.
+exec < /dev/tty
+
+# Execute the code only if pushing to the 'develop' branch
+if [ "$branch" == "avoid-accidental-push-to-develop" ]; then
+    # Warn about the push and ask for confirmation
+    read -p "Are you sure you want to push.? (y/n): " confirmation
+    if [ "$confirmation" != "y" ]; then
+        echo "Push aborted"
+        exit 1
+    fi
 fi
