exit on curl error with an error message

diff --git a/.github/workflows/i18n-weekly-release.yml b/.github/workflows/i18n-weekly-release.yml
--- a/.github/workflows/i18n-weekly-release.yml
+++ b/.github/workflows/i18n-weekly-release.yml
@@ -38,24 +38,77 @@ jobs:
           NAME="Version for internationalization testing $TAG. Not for production."
           BODY='This version is intended to test the internationalization strings. It should NOT be used for production.'
 
+          CREATE_RELEASE_OUT=$(mktemp)
+
           echo "Creating i18n release..."
-          response=$(curl --request POST \
-            --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
-            --header 'Content-Type: application/json' \
-            --data "{\"tag_name\":\"$TAG\",\"target_commitish\":\"develop\",\"name\":\"$NAME\",\"body\":\"$BODY\",\"prerelease\":true}" \
-            https://api.github.com/repos/Automattic/woocommerce-payments/releases)
+          http_code=$(curl --request POST \
+              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+              --header 'Content-Type: application/json' \
+              --data "{\"tag_name\":\"$TAG\",\"target_commitish\":\"develop\",\"name\":\"$NAME\",\"body\":\"$BODY\",\"prerelease\":true}" \
+              --silent \
+              --output "$CREATE_RELEASE_OUT" \
+              --write-out "%{http_code}" \
+              https://api.github.com/repos/Automattic/woocommerce-payments/releases)
+
+          response=$(cat "$CREATE_RELEASE_OUT")
+          rm "$CREATE_RELEASE_OUT"
+
+          if [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then
+            echo "Could not create release:"
+            echo "$response"
+            exit 1
+          fi
+
           echo "Release created."
 
           echo "Uploading i18n assets to GitHub Release..."
+
           upload_url=$(echo $response | grep 'upload_url' | sed 's|.*"upload_url": "\([^{]*\).*|\1|')
 
-          curl --request POST \
+          if [[ -z $upload_url ]]; then
+            echo "No upload URL found in response:"
+            echo "$response"
+            exit 1
+          fi
+
+          UPLOAD_RELEASE_OUT=$(mktemp)
+
+          http_code=$(curl --request POST \
               --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
               --header 'Content-Type: application/zip' \
               --data-binary @woocommerce-payments.zip \
-              "${upload_url}?name=woocommerce-payments.zip"
+              --silent \
+              --output "$UPLOAD_RELEASE_OUT" \
+              --write-out "%{http_code}" \
+              "${upload_url}?name=woocommerce-payments.zip")
+
+          response=$(cat "$UPLOAD_RELEASE_OUT")
+          rm "$UPLOAD_RELEASE_OUT"
+
+          if [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then
+            echo "Could not upload plugin zip to GitHub release:"
+            echo "$response"
+            exit 1
+          fi
           echo "Assets uploaded."
 
           echo "Triggering translations update on GlotPress..."
-          curl --request POST ${{ secrets.GLOTPRESS_IMPORT_URL }}/$TAG
-          echo "Translations update triggered.
+
+          TRIGGER_UPLOAD_OUT=$(mktemp)
+
+          http_code=$(curl --request POST \
+              --silent \
+              --output "$TRIGGER_UPLOAD_OUT" \
+              --write-out "%{http_code}" \
+              ${{ secrets.GLOTPRESS_IMPORT_URL }}/$TAG)
+
+          response=$(cat "$TRIGGER_UPLOAD_OUT")
+          rm "$TRIGGER_UPLOAD_OUT"
+
+          if [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then
+            echo "Could not trigger translations:"
+            echo "$response"
+            exit 1
+          fi
+
+          echo "Translations update triggered."
