fail build task if woocommerce-payments.zip does not exist upon completion

diff --git a/.github/workflows/i18n-weekly-release.yml b/.github/workflows/i18n-weekly-release.yml
--- a/.github/workflows/i18n-weekly-release.yml
+++ b/.github/workflows/i18n-weekly-release.yml
@@ -31,6 +31,11 @@ jobs:
         run: |
           npm ci
           npm run build
+          
+          if [[ ! -f woocommerce-payments.zip ]]; then
+            echo "Failed to create release zip"
+            exit 1
+          fi
 
       - name: Upload release
         run: |
