Better error reporting and curl errors handling

diff --git a/.github/workflows/pre-release-publish-on-tag.yaml b/.github/workflows/pre-release-publish-on-tag.yaml
--- a/.github/workflows/pre-release-publish-on-tag.yaml
+++ b/.github/workflows/pre-release-publish-on-tag.yaml
@@ -29,10 +29,10 @@ jobs:
         id: get_tag
         run: echo ::set-output name=TAG_REF::${GITHUB_REF#refs/tags/}
 
-      - name: Retrive tag information
+      - name: Retrieve tag information
         id: get_tag_info
         env:
-          GITHUB_TAG_URL: ${{ format( 'https://api.github.com/repos/{0}/git/refs/tags/tag-{1}', github.repository, steps.get_tag.outputs.TAG_REF) }}
+          GITHUB_TAG_URL: ${{ format( 'https://api.github.com/repos/{0}/git/refs/tags/{1}', github.repository, steps.get_tag.outputs.TAG_REF) }}
         run: |
           CURL_RESPONSE=$(curl --request GET \
               --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
@@ -44,17 +44,30 @@ jobs:
           CURL_RESPONSE=$(echo "$CURL_RESPONSE" | head -n -1)
 
           if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
-            echo "::error::Could not retrieve tag information from GitHub:"
-            echo "::error::$CURL_RESPONSE" >&2
+            echo "::error::Could not retrieve tag information from GitHub:\n$CURL_RESPONSE"
             exit 1
           fi
           echo "::set-output name=RAW_TAG_DATA::$CURL_RESPONSE"
 
-      - name: Retrive tag object
+      - name: Retrieve tag object
         id: get_tag_object
         env:
           TAG_OBJECT_URL: ${{ fromJson( steps.get_tag_info.outputs.RAW_TAG_DATA ).object.url }}
-        run: echo ::set-output name=RAW_TAG_OBJECT::$(curl "$TAG_OBJECT_URL" )
+        run: |
+          CURL_RESPONSE=$(curl --request GET \
+              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+              --url "$TAG_OBJECT_URL" \
+              --silent \
+              --output - \
+              --write-out "\n%{http_code}\n" )
+          HTTP_CODE=$(echo "$CURL_RESPONSE" | tail -n 1)
+          CURL_RESPONSE=$(echo "$CURL_RESPONSE" | head -n -1)
+
+          if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
+            echo "::error::Could not retrieve tag object from GitHub:\n$CURL_RESPONSE"
+            exit 1
+          fi
+          echo "::set-output name=RAW_TAG_OBJECT::$CURL_RESPONSE"
 
       - name: Enable composer dependencies caching
         uses: actions/cache@v2
@@ -76,13 +89,12 @@ jobs:
           coverage: none
 
       - name: Build release
-        shell: bash
         run: |
           npm ci
           npm run build
 
           if [[ ! -f $RELEASE_FILENAME ]]; then
-            echo "Failed to create release archive $RELEASE_FILENAME"
+            echo "::error::Failed to create release archive $RELEASE_FILENAME"
             exit 1
           fi
 
@@ -90,7 +102,6 @@ jobs:
         env:
           TAG: ${{ steps.get_tag.outputs.TAG_REF }}
         id: get_changelog
-        shell: bash
         run: |
           # pick anything before the first dash as a version number
           VERSION=$(sed -E 's/^([^-]+)-.*/\1/' <<< $TAG)
@@ -109,27 +120,29 @@ jobs:
 
       - name: Create release
         id: create_release
-        shell: bash
         env:
           TAG: ${{ steps.get_tag.outputs.TAG_REF }}
           TAG_MESSAGE: ${{ fromJson( steps.get_tag_object.outputs.RAW_TAG_OBJECT ).message }}
           CHANGELOG: ${{ steps.get_changelog.outputs.CHANGELOG_JSON }}
+          GITHUB_RELEASES_URL: ${{ format( 'https://api.github.com/repos/{0}/releases', github.repository ) }}
         run: |
           NAME=$( echo -n ${TAG_MESSAGE:=$TAG} | jq -aRs '.' )
           echo "Will build a release for tag '$TAG' with the name '$NAME'..."
 
           echo "Creating pre-release..."
-          CURL_RESPONSE=$(curl --request POST \
+          CURL_RESPONSE=$(curl --request GET \
+              --url "$GITHUB_RELEASES_URL" \
               --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
               --header 'Content-Type: application/json' \
               --data "{\"tag_name\":\"$TAG\",\"target_commitish\":\"develop\",\"name\":$NAME,\"body\":$CHANGELOG,\"prerelease\":true}" \
               --silent \
-              --fail \
-              --url "https://api.github.com/repos/${{ github.repository }}/releases")
+              --output - \
+              --write-out "\n%{http_code}\n" )
+          HTTP_CODE=$(echo "$CURL_RESPONSE" | tail -n 1)
+          CURL_RESPONSE=$(echo "$CURL_RESPONSE" | head -n -1)
 
-          if [ $? -ne 0 ]; then
-            echo "Could not create release:"
-            echo "$CURL_RESPONSE"
+          if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
+            echo "::error::Couldn't create GitHub pre-release:\n$CURL_RESPONSE"
             exit 1
           fi
 
@@ -140,16 +153,14 @@ jobs:
         id: upload_release_assets
         env:
           UPLOAD_URL: ${{ fromJson( steps.create_release.outputs.RELEASE_JSON ).upload_url }}
-        shell: bash
         run: |
           echo "Uploading release assets to GitHub release..."
 
           # remove trailing attributes from upload_url
-          upload_url=$(echo $UPLOAD_URL | sed -E 's/([^{]*).*$/\1/')
+          upload_url=$(echo "$UPLOAD_URL" | sed -E 's/([^{]*).*$/\1/')
 
           if [[ -z $upload_url ]]; then
-            echo "No upload URL found in response:" >&2
-            echo "$response" >&2
+            echo "::error::Asset upload URL is missing in response:\n{{ steps.create_release.outputs.RELEASE_JSON }}"
             exit 1
           fi
 
@@ -162,13 +173,12 @@ jobs:
               --output - \
               --write-out "\n%{http_code}\n" )
           HTTP_CODE=$(echo $CURL_RESPONSE | tail -n 1)
+          CURL_RESPONSE=$(echo "$CURL_RESPONSE" | head -n -1)
 
           if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
-            echo "Could not upload plugin archive $RELEASE_FILENAME to GitHub release:" >&2
-            echo "$CURL_RESPONSE" | head -n -1 >&2
+            echo "::error::Couldn't upload plugin archive $RELEASE_FILENAME to GitHub release:\n$CURL_RESPONSE"
             exit 1
           fi
-
           echo "Assets uploaded."
 
       - name: Trigger translations update on GlotPress
@@ -176,19 +186,19 @@ jobs:
         env:
           TAG: ${{ steps.get_tag.outputs.TAG_REF }}
           GLOTPRESS_IMPORT_URL: ${{ secrets.GLOTPRESS_IMPORT_URL }}
-        shell: bash
         run: |
           echo "Triggering translations update on GlotPress..."
 
           CURL_RESPONSE=$(curl --request POST \
+              --url "$GLOTPRESS_IMPORT_URL/$TAG" \
               --silent \
-              --fail \
-              --url "$GLOTPRESS_IMPORT_URL/$TAG")
+              --output - \
+              --write-out "\n%{http_code}\n" )
+          HTTP_CODE=$(echo $CURL_RESPONSE | tail -n 1)
+          CURL_RESPONSE=$(echo "$CURL_RESPONSE" | head -n -1)
 
-          if [ $? -ne 0 ]; then
-            echo "Could not trigger translations:"
-            echo "$CURL_RESPONSE"
+          if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
+            echo "::error::Couldn't trigger translations:\n$CURL_RESPONSE"
             exit 1
           fi
-
           echo "Translations update triggered."
